[package]
name = "scudo-sys"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE.md"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.104"

[build-dependencies]
cc = "1.0.71"
